import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { test } from "node:test";

const appFiles = readdirSync(new URL("../src/app/", import.meta.url)).filter((f) => f.endsWith(".js"));

test("privacy: the app can't connect anywhere, ships no third-party code, and uses no inline styles or scripts", () => {
  const html = readFileSync(new URL("../src/index.html", import.meta.url), "utf8");
  assert.match(html, /connect-src 'none'/);
  assert.doesNotMatch(html.replace(/<!--[\s\S]*?-->/g, ""), /<script[^>]+src="https?:|<script>(?!<\/script>)|style="/);
  assert.ok(appFiles.length >= 6);
  for (const f of appFiles) {
    const src = readFileSync(new URL(`../src/app/${f}`, import.meta.url), "utf8");
    assert.doesNotMatch(src, /fetch\(|XMLHttpRequest|WebSocket|sendBeacon|https?:\/\//, `${f} must not reach the network`);
    assert.doesNotMatch(src, /style="/, `${f}: inline styles are blocked by the CSP`);
  }
});

test("service worker: generated by the build, same-origin only", () => {
  const build = readFileSync(new URL("../build.mjs", import.meta.url), "utf8");
  assert.match(build, /new URL\(r\.url\)\.origin !== location\.origin\) return/);
  assert.match(build, /Network first for everything/); // a deploy must never mix a new page with cached old scripts
});
