// Static build: src/ → dist/, plus the installable-app pieces generated here (no binary files in the repo):
//   - PNG icons (192, 512, maskable 512, and 180 for iOS) rasterized from simple shapes
//   - sw.js: an offline cache of exactly the built files, named by a content hash so updates replace stale caches
import { cpSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { deflateSync } from "node:zlib";
import { join, relative } from "node:path";

const u = (p) => new URL(p, import.meta.url).pathname;
rmSync(u("./dist"), { recursive: true, force: true });
cpSync(u("./src"), u("./dist"), { recursive: true });

// ---- PNG icons: dark rounded square, light dumbbell, accent bar ----
const CRC = Array.from({ length: 256 }, (_, n) => { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; return c >>> 0; });
const crc32 = (buf) => { let c = 0xffffffff; for (const b of buf) c = CRC[(c ^ b) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };
const chunk = (type, data) => { const len = Buffer.alloc(4); len.writeUInt32BE(data.length); const td = Buffer.concat([Buffer.from(type), data]); const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(td)); return Buffer.concat([len, td, crc]); };
function icon(N, fullBleed = false) {
  const px = Buffer.alloc(N * (N * 4 + 1));
  const inRound = (x, y, x0, y0, x1, y1, r) => { if (x < x0 || x > x1 || y < y0 || y > y1) return false; const cx = Math.min(Math.max(x, x0 + r), x1 - r), cy = Math.min(Math.max(y, y0 + r), y1 - r); return (x - cx) ** 2 + (y - cy) ** 2 <= r * r; };
  const pad = fullBleed ? N * 0.12 : 0, s = (N - 2 * pad) / 24;
  const light = [242, 243, 245], accent = [198, 243, 109];
  const shapes = [[3, 9, 5.5, 15, 1, light], [5.5, 7, 8, 17, 1, light], [16, 7, 18.5, 17, 1, light], [18.5, 9, 21, 15, 1, light], [8, 11, 16, 13, 0.3, accent]];
  for (let y = 0; y < N; y++) {
    px[y * (N * 4 + 1)] = 0;
    for (let x = 0; x < N; x++) {
      let c = fullBleed || inRound(x, y, 0, 0, N - 1, N - 1, N * 0.22) ? [17, 18, 20, 255] : [0, 0, 0, 0];
      const gx = (x - pad) / s, gy = (y - pad) / s;
      for (const [x0, y0, x1, y1, r, col] of shapes) if (c[3] && inRound(gx, gy, x0, y0, x1, y1, r)) c = [...col, 255];
      px.set(c, y * (N * 4 + 1) + 1 + x * 4);
    }
  }
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(N, 0); ihdr.writeUInt32BE(N, 4); ihdr[8] = 8; ihdr[9] = 6;
  return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk("IHDR", ihdr), chunk("IDAT", deflateSync(px)), chunk("IEND", Buffer.alloc(0))]);
}
writeFileSync(u("./dist/icon-192.png"), icon(192));
writeFileSync(u("./dist/icon-512.png"), icon(512));
writeFileSync(u("./dist/icon-maskable-512.png"), icon(512, true));
writeFileSync(u("./dist/apple-touch-icon.png"), icon(180, true));

// ---- Service worker: cache exactly these files; the version is their content hash ----
const files = [];
const walk = (d) => readdirSync(d).forEach((f) => { const p = join(d, f); statSync(p).isDirectory() ? walk(p) : files.push(p); });
walk(u("./dist"));
const rel = files.map((f) => relative(u("./dist"), f)).filter((f) => f !== "sw.js").sort();
const hash = createHash("sha256");
rel.forEach((f) => hash.update(f).update(readFileSync(join(u("./dist"), f))));
const version = hash.digest("hex").slice(0, 12);
writeFileSync(u("./dist/sw.js"), `// Generated by build.mjs: offline cache for Setwise ${version}. Same-origin only; your data never passes through here.
const CACHE = "setwise-${version}", FILES = ${JSON.stringify(["./", ...rel.map((f) => `./${f}`)])};
self.addEventListener("install", (e) => e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting())));
self.addEventListener("activate", (e) => e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())));
// Network first for the page itself (so updates arrive when online), cache first for everything else.
self.addEventListener("fetch", (e) => {
  const r = e.request;
  if (r.method !== "GET" || new URL(r.url).origin !== location.origin) return;
  if (r.mode === "navigate") { e.respondWith(fetch(r).then((res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put("./", copy)); return res; }).catch(() => caches.match("./"))); return; }
  e.respondWith(caches.match(r).then((hit) => hit || fetch(r)));
});
`);
console.log(`built dist/ (${rel.length} files, cache ${version})`);
